{{- if .Values.cloudProvider }}
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: {{ .Release.Name }}-cloud-creds
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: {{ .Release.Name }}-cloud-creds
    namespace: {{ .Release.Namespace }}
  {{- if eq .Values.cloudProvider "aws" }}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      {{- toYaml .Values.cloudCredentials.aws.statementEntries | nindent 6 }}
  {{- else if eq .Values.cloudProvider "gcp" }}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
      {{- toYaml .Values.cloudCredentials.gcp.permissions | nindent 6 }}
  {{- end }}
{{- end }}
