# More info: https://docs.docker.com/engine/reference/builder/#dockerignore-file
# Ignore build and test binaries.
bin/
testbin/
# Exclude storage templates from release image
helm-charts/redhat-trusted-profile-analyzer/templates/common/
