# permissions for end users to view trustedprofileanalyzers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rhtpa-operator
    app.kubernetes.io/managed-by: kustomize
  name: trustedprofileanalyzer-viewer-role
rules:
- apiGroups:
  - charts.trustification.io
  resources:
  - trustedprofileanalyzers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.trustification.io
  resources:
  - trustedprofileanalyzers/status
  verbs:
  - get
